name: ethnoby-nuxt
proxy:
  appserver:
    - ethnoby-nuxt.lndo.site
  webserver:
    - ethnoby-build.lndo.site
services:
  appserver:
    type: node:16
    ssl: true
    build_as_root:
      - yarn install
  webserver:
    type: apache
    webroot: dist
    ssl: true
    # build_as_root:
    #   - yarn generate


tooling:
  yarn:
    service: appserver
  dev:
    description: Start serving the project in development mode
    service: appserver
    cmd:
      - echo "============ Starting server for development... ==========="
      - yarn dev --hostname 0.0.0.0 --port 80
  build:
    description: Building the project into static
    service: appserver
    cmd:
      - echo "============ Building project... ==========="
      - yarn build
