name: ethnoby_nuxt
proxy:
  appserver:
    - ethnoby_nuxt.lndo.site
services:
  appserver:
    type: node:16
    command: "yarn dev --hostname 0.0.0.0 --port 80"
    # install_dependencies_as_me:
    #   - yarn install
# events:
#   pre-start:
#     - yarn install

exclude:
  - node_modules
